import { mkdir, writeFile, readFile } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

const CIRCLECI_CONFIG = `# Auto-generated by lemonx — AI-powered test generation, execution, and self-healing fixes
#
# This config runs on a CircleCI machine runner that has the lemon.test platform
# pre-installed. No webhook, no tunnel, no external server needed.
#
# Replace <namespace>/<resource-class> with your CircleCI runner resource class.

version: 2.1

workflows:
  ai-test-and-fix:
    jobs:
      - ai-test-loop:
          filters:
            branches:
              ignore: main

jobs:
  ai-test-loop:
    machine: true
    resource_class: <namespace>/<resource-class>
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run lemon.test AI test-fix loop
          command: |
            echo "🍋 Running AI test generation, execution, and self-healing fixes..."
            cd ~/project

            RESPONSE=$(npx tsx /home/circleci/lemon/src/index.ts 2>&1)

            echo "$RESPONSE"

            if echo "$RESPONSE" | grep -q "⚠️.*Max iterations reached"; then
              echo "⚠️  AI could not fix all tests within the iteration limit"
              exit 1
            fi

            if echo "$RESPONSE" | grep -q "❌"; then
              echo "❌ AI test loop failed"
              exit 1
            fi

            echo "✅ All tests passed"

  ai-generate-tests:
    machine: true
    resource_class: <namespace>/<resource-class>
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Generate AI tests
          command: |
            echo "🍋 Generating tests..."
            npx tsx /home/circleci/lemon/src/index.ts --generate-only

  ai-run-tests:
    machine: true
    resource_class: <namespace>/<resource-class>
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run existing tests
          command: |
            echo "🍋 Running tests..."
            npx vitest run --reporter=verbose
`;

export async function init() {
  const targetDir = process.argv[3] || process.cwd();
  const circleciDir = join(targetDir, ".circleci");

  console.log("🍋 lemonx init — setting up CircleCI AI test integration\n");

  if (!existsSync(targetDir)) {
    console.error(`❌ Directory not found: ${targetDir}`);
    process.exit(1);
  }

  await mkdir(circleciDir, { recursive: true });

  const configPath = join(circleciDir, "config.yml");
  const exists = existsSync(configPath);

  if (exists) {
    const existing = await readFile(configPath, "utf-8");
    if (existing.includes("lemonx") || existing.includes("resource_class")) {
      console.log("⚠️  CircleCI config already contains lemonx integration. Skipping.");
      console.log(`   Config: ${configPath}`);
      return;
    }
    console.log(`⚠️  Existing CircleCI config found at: ${configPath}`);
    console.log("   Back it up before overwriting.\n");
  }

  await writeFile(configPath, CIRCLECI_CONFIG, "utf-8");
  console.log(`✅ CircleCI config written to: ${configPath}`);

  console.log("\nNext steps:");
  console.log("1. Replace <namespace>/<resource-class> in the config with your CircleCI runner resource class");
  console.log("2. Start the lemon.test machine runner:");
  console.log("   docker compose -f docker-compose.runner.yml up -d");
  console.log("\n3. Push to any branch (not main) and CircleCI will trigger the AI test loop!");
}
